/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.imagendiu;


public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logopos = new javax.swing.ButtonGroup();
        canvasImage1 = new com.mycompany.imagendiu.CanvasImage();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        allB = new javax.swing.JCheckBox();
        redB = new javax.swing.JCheckBox();
        greenB = new javax.swing.JCheckBox();
        blueB = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nwB = new javax.swing.JRadioButton();
        swB = new javax.swing.JRadioButton();
        seB = new javax.swing.JRadioButton();
        neB = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout canvasImage1Layout = new javax.swing.GroupLayout(canvasImage1);
        canvasImage1.setLayout(canvasImage1Layout);
        canvasImage1Layout.setHorizontalGroup(
            canvasImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        canvasImage1Layout.setVerticalGroup(
            canvasImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );

        jLabel1.setText("Alejandro García Sosa y Santiago Higuita Ardila");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        allB.setSelected(true);
        allB.setText("Todos");
        allB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allBActionPerformed(evt);
            }
        });

        redB.setSelected(true);
        redB.setText("Rojo");
        redB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redBActionPerformed(evt);
            }
        });

        greenB.setSelected(true);
        greenB.setText("Verde");
        greenB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenBActionPerformed(evt);
            }
        });

        blueB.setSelected(true);
        blueB.setText("Azul");
        blueB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(allB)
                .addGap(18, 18, 18)
                .addComponent(redB)
                .addGap(18, 18, 18)
                .addComponent(greenB)
                .addGap(18, 18, 18)
                .addComponent(blueB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(allB)
                    .addComponent(redB)
                    .addComponent(greenB)
                    .addComponent(blueB))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Seleccione los componentes de color que quiere mostrar");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        logopos.add(nwB);
        nwB.setSelected(true);
        nwB.setText("NW");
        nwB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nwBStateChanged(evt);
            }
        });

        logopos.add(swB);
        swB.setText("SW");
        swB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                swBStateChanged(evt);
            }
        });

        logopos.add(seB);
        seB.setText("SE");
        seB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                seBStateChanged(evt);
            }
        });
        seB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seBActionPerformed(evt);
            }
        });

        logopos.add(neB);
        neB.setText("NE");
        neB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                neBStateChanged(evt);
            }
        });
        neB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(nwB))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(swB)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seB)
                    .addComponent(neB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nwB)
                    .addComponent(neB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seB)
                    .addComponent(swB)))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Seleccione la posición del Logotipo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(191, 191, 191)
                        .addComponent(jLabel4))
                    .addComponent(canvasImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(288, 288, 288))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(canvasImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void allBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allBActionPerformed
        // TODO add your handling code here:
        if(allB.isSelected()){
            redB.setSelected(true);
            greenB.setSelected(true);
            blueB.setSelected(true);
        }else{
            allB.setSelected(true);
        }
        canvasImage1.setImage(UtilsPractica5.seleccionarComponentes(canvasImage1.getImage(), redB.isSelected(), greenB.isSelected(), blueB.isSelected()));
    }//GEN-LAST:event_allBActionPerformed

    private void redBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redBActionPerformed
        // TODO add your handling code here:
        if(!greenB.isSelected() && !blueB.isSelected()){
            redB.setSelected(true);
        }
        if(redB.isSelected() && greenB.isSelected() && blueB.isSelected()){
            allB.setSelected(true);
        }else{
            allB.setSelected(false);
        }
        canvasImage1.setImage(UtilsPractica5.seleccionarComponentes(canvasImage1.getImage(), redB.isSelected(), greenB.isSelected(), blueB.isSelected()));
    }//GEN-LAST:event_redBActionPerformed

    private void greenBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenBActionPerformed
        // TODO add your handling code here:
        if(!redB.isSelected() && !blueB.isSelected()){
            greenB.setSelected(true);
        }
        if(redB.isSelected() && greenB.isSelected() && blueB.isSelected()){
            allB.setSelected(true);
        }else{
            allB.setSelected(false);
        }
        canvasImage1.setImage(UtilsPractica5.seleccionarComponentes(canvasImage1.getImage(), redB.isSelected(), greenB.isSelected(), blueB.isSelected()));
    }//GEN-LAST:event_greenBActionPerformed

    private void blueBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueBActionPerformed
        // TODO add your handling code here:
        if(!greenB.isSelected() && !redB.isSelected()){
            blueB.setSelected(true);
        }
        if(redB.isSelected() && greenB.isSelected() && blueB.isSelected()){
            allB.setSelected(true);
        }else{
            allB.setSelected(false);
        }
        canvasImage1.setImage(UtilsPractica5.seleccionarComponentes(canvasImage1.getImage(), redB.isSelected(), greenB.isSelected(), blueB.isSelected()));
    }//GEN-LAST:event_blueBActionPerformed

    private void neBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_neBActionPerformed

    private void neBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_neBStateChanged
        // TODO add your handling code here:
        if(neB.isSelected()){
            canvasImage1.setPos(1);
        }
    }//GEN-LAST:event_neBStateChanged

    private void seBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seBActionPerformed

    private void seBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_seBStateChanged
        // TODO add your handling code here:
        if(seB.isSelected()){
            canvasImage1.setPos(2);
        }
    }//GEN-LAST:event_seBStateChanged

    private void swBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_swBStateChanged
        // TODO add your handling code here:
        if(swB.isSelected()){
            canvasImage1.setPos(3);
        }
    }//GEN-LAST:event_swBStateChanged

    private void nwBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nwBStateChanged
        // TODO add your handling code here:
        if(nwB.isSelected()){
            canvasImage1.setPos(0);
        }
    }//GEN-LAST:event_nwBStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox allB;
    private javax.swing.JCheckBox blueB;
    private com.mycompany.imagendiu.CanvasImage canvasImage1;
    private javax.swing.JCheckBox greenB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.ButtonGroup logopos;
    private javax.swing.JRadioButton neB;
    private javax.swing.JRadioButton nwB;
    private javax.swing.JCheckBox redB;
    private javax.swing.JRadioButton seB;
    private javax.swing.JRadioButton swB;
    // End of variables declaration//GEN-END:variables
}
